CIRCUITPY_CREATOR_ID = 0x239A
CIRCUITPY_CREATION_ID = 0x80D8
USB_PRODUCT = "micro:bit v1"
USB_MANUFACTURER = "BBC"

MCU_CHIP = nrf51822

CIRCUITPY_BUILD_EXTENSIONS = combined.hex

INTERNAL_FLASH_FILESYSTEM = 1

# USB pins aren't used.
CIRCUITPY_USB = 0
